creation_rules:
  # Encrypt any file in kubernetes/secrets/ or anything ending in .sops.yaml
  - path_regex: kubernetes/secrets/.*\.ya?ml$
    age: "age19juxqkka8l38vgnjuwtn20cmmsffeqftcraj0a88720c3fzw7f0qxcvx89"

  - path_regex: infrastructure/secrets/.*\.ya?ml$
    age: "age19juxqkka8l38vgnjuwtn20cmmsffeqftcraj0a88720c3fzw7f0qxcvx89"

  # Fallback for any explicitly named SOPS file
  - path_regex: .*\.sops\.ya?ml$
    age: "age19juxqkka8l38vgnjuwtn20cmmsffeqftcraj0a88720c3fzw7f0qxcvx89"
