services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
    volumes:
      - ./data:/data
      - ./music:/music:ro
    networks:
      - proxied-net
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "navidrome"
      tsdproxy.container_port: "4533"

networks:
  proxied-net:
    external: true
