services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      - ./config:/config
      - ./metadata:/metadata
      - /your/media/path
    environment:
      - TZ=Your/Timezone
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
    restart: unless-stopped
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=audiobookshelf"
      - "tsdproxy.container_port=80"
    networks:
      - proxied-net

networks:
  proxied-net:
    external: true

